name: All Tests Sequentially

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  Chrome_Ubuntu_All_Tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml up --scale chrome=2 --scale edge=0 --scale firefox=0 -d

      - name: Check Running Containers
        run: docker ps

      - name: Run cucumber tests
        continue-on-error: true
        run: >
          mvn test
          -Dcucumber.glue="CucumberStepDefinitions"
          -Dcucumber.features="src/test/resources/FeatureFiles"
          -Dcucumber.filter.tags="@regression"
          -DexecutionType="Remote"
          -DbrowserType="Chrome"
          -DisHeadless="true"
          -Ddataproviderthreadcounts="1"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report All Tests Sequentially Chrome Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml down
